### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by nvdlug** [simlu/yaml-boost#74]
Hi,

Ive installed this pluging hoping that it will help me merge map my environment variables.
I've defined the serverless.js exactly like the example on readme.

However, when I run the deploy command I get the 
"error Line: 1 Char: 1 Syntax error in serverless.js"

And with "sls print" it says: 
Serverless plugin "yaml-boost" initialization errored: Plugin is not a constructor

Any ideas? I am running Node 10.3 with packages:

  "dependencies": {
    "envelope": "^1.0.7",
    "node-pop3": "^0.1.0",
    "nodemailer": "^4.0.1",
    "optimist": "^0.6.1",
    "yaml-boost": "^1.7.1"
  }

**Comment by simlu** [comment]
We are using this im production right now with no problems with

```
const path = require("path");
// eslint-disable-next-line import/no-extraneous-dependencies
const optimist = require('optimist');
// eslint-disable-next-line import/no-extraneous-dependencies
const yaml = require("yaml-boost");

module.exports = yaml.load(path.join(__dirname, "serverless.wrapper.yml"), optimist.argv);
```
Maybe the readme is outdated?

We haven't tested node 10, but it should work fine.

The yaml boost and optimist both should be dev dependencies (unless you're loading them elsewhere).

Can you test if above fixes your issue?

**Comment by simlu** [comment]
Wait.. Do you use yaml boost as a plugin in your serverless file? That error is a bit confusing

**Comment by nvdlug** [comment]
Are you not supposed to put the plugin in the serverless.yml ? Sorry Im a bit new to serverless stuff. Is this stacktrace good enough? 

```0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'preview-yaml',
1 verbose cli   '--scripts-prepend-node-path=auto' ]
2 info using npm@6.1.0
3 info using node@v10.3.0
4 verbose run-script [ 'preview-yaml' ]
5 info lifecycle lambdatutorial@1.0.0~preview-yaml: lambdatutorial@1.0.0
6 verbose lifecycle lambdatutorial@1.0.0~preview-yaml: unsafe-perm in lifecycle true
7 verbose lifecycle lambdatutorial@1.0.0~preview-yaml: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\derekv\OneDrive - TEST Group\customer_solutions\cg_lambda\cg_lambda\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\Microsoft MPI\Bin\;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Program Files\Java\jdk-9.0.4\bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\MiKTeX 2.9\miktex\bin\x64\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files\dotnet\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\nodejs\;C:\Gradle\bin;C:\Program Files\Git\cmd;C:\Users\derekv\AppData\Local\Microsoft\WindowsApps;C:\Users\derekv\AppData\Roaming\MiKTeX\2.9\miktex\bin\x64\;;C:\Program Files\Microsoft VS Code\bin;C:\Users\derekv\AppData\Roaming\npm
8 verbose lifecycle lambdatutorial@1.0.0~preview-yaml: CWD: C:\Users\derekv\OneDrive - TEST Group\customer_solutions\cg_lambda\cg_lambda
9 silly lifecycle lambdatutorial@1.0.0~preview-yaml: Args: [ '/d /s /c', 'sls print' ]
10 silly lifecycle lambdatutorial@1.0.0~preview-yaml: Returned: code: 1  signal: null
11 info lifecycle lambdatutorial@1.0.0~preview-yaml: Failed to exec preview-yaml script
12 verbose stack Error: lambdatutorial@1.0.0 preview-yaml: `sls print`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:304:16)
12 verbose stack     at EventEmitter.emit (events.js:182:13)
12 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
12 verbose stack     at ChildProcess.emit (events.js:182:13)
12 verbose stack     at maybeClose (internal/child_process.js:961:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
13 verbose pkgid lambdatutorial@1.0.0
14 verbose cwd C:\Users\derekv\OneDrive - TEST Group\customer_solutions\cg_lambda\cg_lambda
15 verbose Windows_NT 10.0.17134
16 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "preview-yaml" "--scripts-prepend-node-path=auto"
17 verbose node v10.3.0
18 verbose npm  v6.1.0
19 error code ELIFECYCLE
20 error errno 1
21 error lambdatutorial@1.0.0 preview-yaml: `sls print`
21 error Exit status 1
22 error Failed at the lambdatutorial@1.0.0 preview-yaml script.
22 error This is probably not a problem with npm. There is likely additional logging output above.
23 verbose exit [ 1, true ]```

**Comment by nvdlug** [comment]
@MacMcIrish Thanks, I figured as much. I basically want to do exactly the same as simlu wanted at https://github.com/serverless/serverless/issues/4571

After reinstalling everything it seems to work, but now I have this:
```
  environment:
    TEST: "TEST"
    <<<:
    ${file(env.yml):${self:provider.stage}}
```
But it says; 
``` 
can not read an implicit mapping pair; a colon is missed at line 41, column 44:
     ... env.yml):${self:provider.stage}}
```

Do you know how to fix this?

**Comment by simlu** [comment]
Checking the example, `<<<` requires a list.
```js
    <<<:
      - ...
      - ...
```

**Comment by nvdlug** [comment]
I see,

It sorta works now. However my env.yml  looks like this.

```
dev:
  TABLE_NAME: "concertgebouw_dev"
prod:
  TABLE_NAME: "concertgebouw_prod"
```

When I reference it dynamically with 

```
  stage: dev
  environment:
    TEST: "TEST"
    <<<:
      - ${file(env.yml):${self:provider.stage}}
```

I get 

```
  environment:
    '0': $
    '1': '{'
    '2': f
    '3': i
    '4': l
    '5': e
    '6': (
    '7': e
    '8': 'n'
    '9': v
    '10': .
    '11': 'y'
    '12': m
    '13': l
    '14': )
    '15': ':'
    '16': $
    '17': '{'
    '18': s
    '19': e
    '20': l
    '21': f
    '22': ':'
    '23': p
    '24': r
    '25': o
    '26': v
    '27': i
    '28': d
    '29': e
    '30': r
    '31': .
    '32': s
    '33': t
    '34': a
    '35': g
    '36': e
    '37': '}'
    '38': '}'
    TEST: TEST
``` 

It works as expected when I reference it like ` - ${file(env.yml):dev}`` Is that intended?

**Comment by simlu** [comment]
Variables in sub-selects are not supported atm. Feel free to open a ticket.

We are using separate files (lot cleaner when you have more env vars) `${file(config/${opt:stage}.yml)}`

**Comment by nvdlug** [comment]
Ok thanks a lot I will just use different files : )

**Comment by simlu** [comment]
How do you define `${self:provider.stage}`? You might be able to use opt directly?

**Comment by nvdlug** [comment]
Indeed

```
  environment:
    TEST: "TEST"
    <<<:
      - ${file(env.yml):${opt:stage, 'dev'}}
``` 

Seems to work fine as well

**Comment by simlu** [comment]
Kk. Yeah self isn't supported cause then you really need to deal with recursion properly.

Anything else or are you happy with this for now?

**Comment by nvdlug** [comment]
Nope I'm fine now. I am just wondering why it wont work with "severless" alias instead of "sls". Is there any difference between the two? Pic of error: http://prntscr.com/k0hx3r

**Comment by simlu** [comment]
Not as far as I know. However we always use `sls`, so there might be a difference?

Might be time to ask on the serverless github.

**Comment by nvdlug** [comment]
Ok I will, thanks again for your patience. Ill keep an eye out on the ticket you made!

**Comment by simlu** [comment]
Closing this for now. Feel free to open a new ticket if you have further questions.
